environment: dev
basedir: /home/dlink/hip

database:
   engine : mysql
   db     : hip
   host   : localhost
   user   : hip
   passwd : $MOTIVIZDB_PASS
   dictcursor: True

logging:
   dir: /home/dlink/log
   filename: /home/dlink/log/motiviz.log
   level: DEBUG
